version: '3.1'

services:
  elasticsearch:
    container_name: elasticsearch-instance
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana-instance
    image: docker.elastic.co/kibana/kibana:8.8.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASRICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

  filebeat:
    container_name: filebeat-instance
    image: docker.elastic.co/beats/filebeat:8.8.1
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/tmp/worker/logs/
    labels:
      - co.elastic.logs/json.overwrite_keys=true
      - co.elastic.logs/json.add_error_key=true
      - co.elastic.logs/json.expand_keys=true
    depends_on:
      - kibana
    networks:
      - elastic

  worker:
    container_name: worker-instance
    build:
      context: .
      dockerfile: dev-dockerfile
    image: worker
    working_dir: /tmp/worker
    volumes:
      - .:/tmp/worker
    tty: true
    depends_on:
      - kibana
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
  .:
  filebeat.yml:
  logs: