filebeat.inputs:
- type: filestream 
  paths: /tmp/worker/logs/*.json
  parsers:
    - ndjson:
      overwrite_keys: true 
      add_error_key: true 
      expand_keys: true 

processors: 
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

output.elasticsearch.index: "ls-sbs-poc"
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.template.name: "ls-sbs-poc"
setup.template.pattern: "ls-sbs-poc"